### ISSUE TITLE
issue while compling

### ISSUE THREAD

**Issue by PieterGit** [WickedDevice/AQEV2FW#21]
i get the following error when compiling:

AQEV2FW.ino:5:19: fatal error: SdFat.h: No such file or directory
compilation terminated.
Fout bij compileren.

**Comment by vicatcu** [comment]
Seems like maybe you're using an older version of the Arduino Board Support Package. Please can you check that your Boards Manager URL contains: http://update.wickeddevice.com/package_airqualityegg-2.0.4-alpha_index.json

If not, you need to replace what you've got with that, then go into Tools => Boards Manager and install it, then probably restart your IDE.

Also make sure you've selected "WildFire v3 [dual-optiboot]" from the Tools => Boards menu. Then you should be good.

**Comment by PieterGit** [comment]
fixed myself. installed  https://github.com/greiman/SdFat

To use SdFat, clone the repository or unzip the ZIP file and place the SdFat
folder into the libraries sub-folder in your main sketch folder.

The dependencie is listed on the homepage but somehow I forgot to install.
Issue can be closed.

**Comment by vicatcu** [comment]
You're doing it old school :+1:  hehe

**Comment by PieterGit** [comment]
my boards url was 
http://update.wickeddevice.com/package_airqualityegg-2.0.2-beta_index.json

well i'm newbie in arduino programming. 
i somehow managed to be able to get the readings ok in the csv/console, but on the display of the aqe itself. it keeps listing question marks in stead of the value (even after the warming up)

it now booted with the modelname/type, so i hope i fixed that by changing my board url.

**Comment by PieterGit** [comment]
using the new board url fixed that issue. see if this firmware fixes the frequent restarts, see https://personal.xively.com/feeds/759060959

glad CO is 0.0 now, previous version sometimes gave values that weren't really true (and i'm still alive)
