### ISSUE TITLE
feature request: display measurements on lcd in offline mode

### ISSUE THREAD

**Issue by PieterGit** [WickedDevice/AQEV2FW#25]
e.g. "use lcd" which is true by default.
the firmware 2.0.4 displays "LOGGING DATA TO USB-SERIAL" but I'll prefer to see the measurements on the display.

**Comment by vicatcu** [comment]
@PieterGit do you have any ideas on how to visually differentiate the operating mode on the display at runtime (i.e. after startup) if we implement this feature? If I there's a better/smarter way to do that than what we are doing now, I too would prefer to show the readings on the display no matter what mode we are in.

**Comment by vicatcu** [comment]
Moved to https://github.com/WickedDevice/AQEV2FW_NO2CO_ESP/issues/8
