### ISSUE TITLE
enhancement: use offline mode without an sdcard and only use usb/serial output

### ISSUE THREAD

**Issue by PieterGit** [WickedDevice/AQEV2FW#5]
I want to use the AQE in offline mode and use a USB-cable to get the reading to my raspberry pi using a python script that uses PySerial.

I don't need the readings written to the AQE sdcard.

Is it possible to change printCsvDataLine  function so that in case 
((mode == SUBMODE_OFFLINE) && !init_sdcard_ok)

it prints  

setLCD_P(PSTR("  LOGGING DATA  "
                    "   TO SERIAL-USB   "));   

BTW I'm new to Arduino programming. Is there any guide / documentatino in how to program an AQE v2 available?

**Comment by vicatcu** [comment]
@PieterGit yea that seems like a more accurate message, I'll push an update in a few minutes... as far as programming AQEv2 there's not a programming guide, but here's some instructions that will get you up and running pretty quickly I think.
1. Download Arduino 1.6.4 or later and launch it.
2. Select File=>Preferences and add "http://update.wickeddevice.com/package_airqualityegg-2.0.2-beta_index.json" to the "Additional Boards Manager URLs" file and click OK.
3. Select Tools=>Boards=>Boards Manager... which should open a dialog
4. Air Quality Egg by Wicked Device LLC should show up at the bottom of the list
5. Click on it and then click "Install" and it should download all the hardware descriptions and libraries needed.
6. Select Boards=>"WildFirev3 [dual-optiboot]
7. Select File=>Examples=>AQEV2FW=>AQEV2FW
8. That should open the production sketch
9. Select Sketch=>Compile/Verify and it should compile without errors.
10. With the Egg USB cable connected to the computer you should be able to select its port from the Tools=>Port menu.
11. Select File=>Upload and the firmware should be uploaded.

**Comment by vicatcu** [comment]
I just pushed an update to GitHub with the requested change. If you follow my steps above, you'll have to make the change in the AQEV2FW sketch (it's not included in the update package right now, only on github).

**Comment by vicatcu** [comment]
Addressed by https://github.com/WickedDevice/AQEV2FW/commit/7f7b284e477cf269cfdb5420f746acd073fed6a8
