### ISSUE TITLE
Atmospheric Pressure Compensation

### ISSUE THREAD

**Issue by WickedDevice** [WickedDevice/AQEV2FW#7]
Some inquiry suggests there may be a linear response effect due to atmospheric pressure. That is to say At 0.9 atmospheres, the sensors response would be 90% of what it would be at 1 atmosphere. Add a configurable parameter that allows one to compensate for that effect (e.g. implement an 'altitude' command, that sets an atmospheric_pressure_coefficient value in EEPROM, and then uses it to adjust reported concentration at runtime).

**Comment by vicatcu** [comment]
Wikipedia describes some formulas for characterizing pressure variation with altitude [here](https://en.wikipedia.org/wiki/Atmospheric_pressure#Altitude_variation). [This article](http://www.pnas.org/content/95/24/14009.full) discusses population distribution across altitudes, which suggests that the vast majority of the Earth's population resides below an altitude of 2500 meters above sea level.
