### ISSUE TITLE
Temperature Compensation Formula Fix

### ISSUE THREAD

**Issue by WickedDevice** [WickedDevice/AQEV2FW#9]
I think there's a sign error in the temperature compensation formula (still analyzing datasheets to be sure).

Specifically, "1.0f +" possibly needs to be changed to "1.0f -" on [this line](https://github.com/WickedDevice/AQEV2FW/blob/master/AQEV2FW.ino#L4613), and probably also on [this line](https://github.com/WickedDevice/AQEV2FW/blob/master/AQEV2FW.ino#L4544). 

Also consider whether a higher fidelity correction is merited. Current model is a simple two-piece linear estimation).

**Comment by WickedDevice** [comment]
Published [this blog post](http://shop.wickeddevice.com/2015/07/14/temperature-compensation/) describing in more detail about Temperature Compensation.

**Comment by vicatcu** [comment]
Expanding this issue to include baseline offset compensation.

**Comment by vicatcu** [comment]
Published this [blog post](http://shop.wickeddevice.com/2015/08/05/temperature-compensation-part-deux/) describing in more detail about Baseline Offset Temperature Compensation, as well as supporting simulation and modeling.
